trivia/urls.py
from django.urls import path

from .views import (
	HomeListView, 
	QuestionDetailView, 
	check_answer,
	ResultPageView,
)


app_name = 'trivia'

urlpatterns = [
	path('', HomeListView.as_view(), name='home'),
	path('<str:category_name>/<int:pk>/', QuestionDetailView.as_view(), name='question_page'),
	path('<str:category_name>/<int:pk>/check/', check_answer, name='check_answer'),
	path('result/', ResultPageView.as_view(), name='result'),
]

trivia_show/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('', include('trivia.urls')),
    path('admin/', admin.site.urls),
]

trivia/models.py
from django.db import models
from django.urls import reverse, reverse_lazy


class Category(models.Model):
	name = models.CharField(max_length=200)

	# def get_absolute_url(self):
	# 	return reverse('home')

	def __str__(self):
		return self.name


class Question(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	question_text = models.TextField(max_length=200)

	def __str__(self):
		return self.question_text

	def get_absulute_url(self):
		return reverse_lazy('question_page', args=[str(category.name), str(self.id)])


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	is_correct_answer = models.BooleanField()

	def __str__(self):
		return self.choice_text

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
	age = models.PositiveIntegerField(null=True, blank=True)


class Game(models.Model):
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	score = models.PositiveIntegerField(null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = CustomUser
		fields = UserCreationForm.Meta.fields + ('age',)


class CustomUserChangeForm(UserChangeForm):

	class Meta:
		model = CustomUser
		fields = UserChangeForm.Meta.fields

trivia/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from trivia.models import Category, Question, Choice


class HomeListView(ListView):

	template_name = 'home.html'
	
	def get_queryset(self):
		self.request.session['score'] = 0
		return Category.objects.all()

class QuestionDetailView(DetailView):

	template_name = 'question.html'

	def get_queryset(self):
		self.category = get_object_or_404(Category, name=self.kwargs['category_name'])
		return Question.objects.filter(category=self.category)


def check_answer(request, category_name, pk):
	question = get_object_or_404(Question, pk=pk)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
		if selected_choice.is_correct_answer == True:
			request.session['score'] += 10
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'question.html', {
			'question': question,
			'error_message': "You did not select a choice...",
		})
	else:
		category = get_object_or_404(Category, name=category_name)
		if Question.objects.filter(category=category, pk=pk+1).exists():
			return HttpResponseRedirect(reverse('trivia:question_page', args=(category_name, pk+1,)))
		else:
			return HttpResponseRedirect(reverse('trivia:result'))


class ResultPageView(TemplateView):
	template_name = 'result.html'

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TheGreatestTrivia</title>
</head>

<body>
	<header>
		<h1>The Greatest Trivia Show on Earth!</h1>
	</header>

	<div>
		<h3>{% block question_text %}{% endblock %}</h3>
		{% block error_message %}
		{% endblock %}
		{% block choice_content %}
		{% endblock %}
	</div>

	<div>
		{% block score %}
		{% endblock %}
	</div>
</html>

templates/home.html
{% extends 'base.html' %}

{% block question_text %}Choose a category!{% endblock %}

{% block choice_content %}
<ul>
	{% for category in object_list %}
		<li><a href="{% url 'trivia:question_page' category.name category.question_set.first.pk %}">{{ category.name }}</a></li>
	{% endfor %}
</ul>
{% endblock %}

templates/question.html
{% extends 'base.html' %}

{% block question_text %}
	{{ question.question_text }}
{% endblock %}

{% block error_message %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock %}

{% block choice_content %}
	<form method="post" action="{% url 'trivia:check_answer' question.category.name question.id %}">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
		<div>
			<input type="radio" id='choice{{ forloop.counter }}' name="choice" value="{{ choice.pk }}" />
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
		</div>
		{% endfor %}

		<button type="submit">Next</button>
	</form>
{% endblock %}

{% block score %}
	<h3>Score: <span>{{ request.session.score }}</span></h3>
{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% block choice_content %}

<h2>Ha! Your score is <span>{{ request.session.score }}</span></h2>

<a href="{% url 'trivia:home' %}">Back to home</a>

{% endblock %}

trivia/templates/trivia/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TheGreatestTrivia</title>
</head>

<body>
	<header>
		<h1>The Greatest Trivia Show on Earth!</h1>
	</header>

	<div>
		<h3>{% block question_text %}{% endblock %}</h3>
		<form method="POST">
			{% csrf_token %}
			{% block table %}
			{% endblock %}
		</form>
	</div>
</html>